export const ADD_SUBJECT = "ADD_SUBJECT";
export const ADD_STUDENT = "ADD_STUDENT";

export const DEREG_STUDENT = "DEREG_STUDENT";

export const ADD_ALL_STUDENTS = "ADD_ALL_STUDENTS";
export const MINUS_ALL_STUDENTS = "MINUS_ALL_STUDENTS";


export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";

export const LOAD_DEMODATA = "LOAD_DEMODATA";
export const LOAD_OWNDATA = "LOAD_OWNDATA";
